MAX_INVENTORY = 0.05         # Maximum long or short inventory
MAX_DRAWDOWN = -100.0        # Max allowed PnL loss before halting
MAX_SPREAD_PCT = 0.015      # Max spread (% of best bid) to quote into
MAX_VOLATILITY = 20
TICK_SIZE = 0.01            # smallest unit to trade
COOLDOWN_PERIOD = 2         # seconds
MIN_NOTIONAL = 10           # minimum trade amount (in $)
PRICE_TOLERANCE = 0.05      # For real world simulation for accepted market orders
CONFIDENT_BUY = 1          # If you are confident of the buy then buy this much qty
WINDOW = 10
THRESHOLD = 0.1
INVENTORY_SENSITIVITY = 0.1
NEWS_THRESHOLD = 0.8        # threshold for news to be sentimental before we trade it
FINNUB_API_KEY = "#"
POLYGON_API = "#"